### ISSUE TITLE
[OpenPro]开源社区评审过程度量体系及其实证研究

### ISSUE THREAD

**Issue by zhuxiangning** [X-lab2017/open-research#85]
本周组会（6月6日）计划阅读本篇论文
论文已经入库[openlist_No.37](https://github.com/X-lab2017/open-research/blob/main/openlist.md)，直接走推荐流程
- Title: 开源社区评审过程度量体系及其实证研究
- Year: 2021
- Author and affiliation: 蒋竞，吴秋迪，张莉
- Conference or Journal: 软件学报
- Rank: 中文期刊 A
- Keywords: 开源社区，代码评审，度量体系，决策者，软件缺陷
- Link: [开源社区评审过程度量体系及其实证研究](https://xlab2017.yuque.com/msdpvs/dtg7ew/26296152)
- Selecting Reason: 建立评审过程度量体系，能够了解代码评审情况，促进提高开源软件项目质量.
- Supplementary: 暂无

**Comment by birdflyi** [comment]
Guides for Papers already in [openlist](https://github.com/X-lab2017/open-research/blob/main/openlist.md):
- Add this share info into the README.md file in [agenda](https://github.com/X-lab2017/open-research/tree/main/agenda).
- [Share the paper and prepare for other outcomes...]
- Update the record in [openlist](https://github.com/X-lab2017/open-research/blob/main/openlist.md) and close this issue.

Take a try with example: Issue #69 fixed by PR #70 .

**Comment by xiaoya-Esther** [comment]
主题: X-lab 论文分享组会
日期: 2022-06-06 20:28:02
录制文件：https://meeting.tencent.com/v2/cloud-record/share?id=ecabb51e-a1fe-404e-a26e-5f72e14e8c01&from=3
